application: xx450sharestuff
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  
- url: .*
  script: main.application

libraries:
- name: django
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'sharestuffproject.settings'